### ISSUE TITLE
Core.getConfiguration().getDTAPMode() was removed in Mendix 6.0.0

### ISSUE THREAD

**Issue by jpulleman** [ako/CsvServices#2]
This leads to an issue in the action: CsvServices/javasource/csvservices/actions/CsvExportInitializeAction.java

`        boolean isSandbox = Core.getConfiguration().getApplicationRootUrl().contains(".mendixcloud.com") && "DEVELOPMENT".equalsIgnoreCase(Core.getConfiguration().getDTAPMode().toString());
        isSandbox = true;
        if (isSandbox) {`

Should probably be replaced with a Constant.

**Comment by ako** [comment]
This is no longer required, as we don't have to do anything special for sandboxes. The request handler can now be attached to /csv. I've removed the code.
