### ISSUE TITLE
csvServices version 1.1 Post issue with Mendix System attributes 'changedDate', 'createdDate'

### ISSUE THREAD

**Issue by hln98** [ako/CsvServices#3]
Hello,

Absolutely love your csvService app.

I am having problem, importing in csv data into my Mendix application, using csvServices version 1.1 whenever my entity has a ‘changedDate’. 

My entity has a ‘changedDate’ attribute (it is a system member).   When I run a Post that reads in a csv input file with just 1 row of data and inserts it into my Entity in Mendix, I got the error of “write access denied for member ‘changedDate’ since it is a system attribute.

I tried not including the changedDate column and data in my csv input file but getting nullpointerException since it expects the column and data to be in the input file.

The input record will not insert because of this error.  

1.  Is there any way around this? 
2.  Does your latest version of csvServices have a work-around for this? 

 failed to create object: Write access denied for member 'changedDate'failed to create object: Write access denied for member 'changedDate' 

Thanks.

Hoang

**Comment by ako** [comment]
Starting release 2.3 you can exclude these columns using an alternative header.
